### ISSUE TITLE
UUID for pipeline config not available

### ISSUE THREAD

**Issue by HenningL** [jenkinsci/aws-codecommit-trigger-plugin#49]
I want to make the plugin work in the pipeline with jenkinsfile:
properties([pipelineTriggers([$class: "com.ribose.jenkins.plugin.awscodecommittrigger.SQSTrigger", queueUuid: "cant find it"]])])

The other aws-sqs plugin shows a uuid in the advanced section which is working but its triggering all jobs on that queue as mentioned in doc.

I cant find a queueUuid anywhere to configure the plugin correctly.

So, where can i find it?

**Comment by HenningL** [comment]
Ok, with the help of logs, the code i made it work. 

**queueUuid can be found in the <plugin>.xml inside the jenkins folder on the machine.**

properties([$class: "com.ribose.jenkins.plugin.awscodecommittrigger.SQSTrigger", queueUuid: "from the plugin.xml", subscribeInternalScm:true]])])

Without the second param 'subscribeInternalScm' the plugin will not find configured scm.

Consider to put it in the docs.
Consider to publish the queueUuid in jenkins-config-view after submitting queue config.

**Comment by phuonghuynh** [comment]
thanks @HenningL 
We will introduce pipeline syntax for easy use soon
